name: Checklist status changed
on:
  pull_request:
    types: [edited]
jobs:
  pr_checklist_changed:
    name: PR Checklist changed
    # TODO: Only if check changed
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$GITHUB_CONTEXT"
