name: Block untested PR
on:
  pull_request:
    types: [opened, synchronize, reopened] # TODO: Test if synchronize works
    # TODO: We should not force tests for all commits, only specific changes
jobs:
  block-untested:
    name: Block untested commits
    if: github.base_ref == 'main' || github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: mkdir checks
      - run: echo "test" >> checks/check-info.json
      - name: Upload block file
        uses: actions/upload-artifact@v4
        with:
          name: check-info.json
          path: checks/check-info.json
          retention-days: 1
          overwrite: true
      - name: Fail check
        run: |
          echo "Disabled merging because the latest commit has not been automaticly tested yet"
          exit 1
      # Step 1: Checkout branch
      # Step 2: Calculate changeset and check if block should be triggered
      # Step 3.1: Block PR if not tested
      # 3.2: Unblock PR if
