name: Checklist status changed
on:
  issue_comment:
    types: [edited]
jobs:
  pr_checklist_changed:
    name: PR Checklist changed
    # TODO: Only if check changed
    runs-on: ubuntu-latest
    steps:
      - name: Check run
        uses: bahmutov/should-run-github-action@v1
        id: check-pr
        with:
          checkbox_text: 'Run automatic test'
        env:
          GITHUB_EVENT: ${{ toJson(github.event) }}
      - name: Should trigger
        if: ${{ steps.check-pr.outputs.shouldRun }}
        run: echo "Running"
