name: New PR opened
on:
  pull_request:
    types: [opened, reopened]
    # TODO: We should not force tests for all commits, only specific changes
jobs:
  new-pr-opened:
    name: New PR opened
    if: github.base_ref == 'main' || github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Disabled merging because the latest commit has not been automaticly tested yet"
          exit 1
      # Step 1: Checkout branch
      # Step 2: Calculate changeset and check if block should be triggered
      # Step 3.1: Block PR if not tested
      # 3.2: Unblock PR if
