# TODO:
# OnCommit / Push (tbd)
# runs-on: linux
# Checkout code
name: Run unit tests (PHPUnit)
on:
  pull_request:
    types: [opened, reopened, synchronize]
jobs:
  unit-tests:
    timeout-minutes: 30
    # if: github.base_ref == 'main' || github.base_ref == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            cypress
      - run: |
          echo "Disabled merging because the latest commit has not been automaticly tested yet"
          ls
      # Step 1: Checkout branch
      # Step 2: Calculate changeset and check if block should be triggered
      # Step 3.1: Block PR if not tested
      # 3.2: Unblock PR if
