name: Checklist status changed
on:
  pull_request:
    types: [edited]
jobs:
  pr_checklist_changed:
    name: PR Checklist changed
    # TODO: Only if check changed
    runs-on: ubuntu-latest
    steps:
      - run: echo "Checkbox changed"
